### ISSUE TITLE
piplock file

### ISSUE THREAD

**Issue by vikramnr** [edrickdch/chat-pdf#1]
> According to pypa/pipenv#598, it is recommended to include Pipfile.lock in version control. However, in case of collaboration, if having platform-specific dependencies or dependencies having no cross-platform support, pipenv may install dependencies that don't work, or not install all needed dependencies.

It doesn't work for in windows, I thinks better to specify this in README incase of issues to delete the file and run the `pipenv install`

**Comment by edrickdch** [comment]
Thanks @vikramnr, I added a note to the README file
