### ISSUE TITLE
Hi Edrick, thans for your great repo. but I got this error. can you suggest something?

### ISSUE THREAD

**Issue by Erdem-Atik** [edrickdch/chat-pdf#2]
Traceback (most recent call last):
  File "d:\CODING\PYTHON\langChain1.1\chat-pdf\src\ingest.py", line 116, in <module>
    raw_pages, metadata = parse_pdf(file_path)
                          ^^^^^^^^^^^^^^^^^^^^
  File "d:\CODING\PYTHON\langChain1.1\chat-pdf\src\ingest.py", line 54, in parse_pdf
    raise FileNotFoundError(f"File not found: {file_path}")
FileNotFoundError: File not found: src/data/april-2023.pdf

**Comment by edrickdch** [comment]
Unfamiliar with Windows, but seems like this is relative path issue.

Can you confirm you ran the python script according to step #6 from the readme (running the ingest.py file from the top level directory):

``` bash
python src/ingest.py
```

**Comment by edrickdch** [comment]
Will consider this as resolved
